=== fanste98/ist2020/oglasi.dtd
<!ELEMENT Oglasi (Oglas+)>

<!ELEMENT Oglas (KategorijaOglasa,DatumIsteka,Cena,TekstOglasa,(Oznaka+),(Email+))>

<!ELEMENT KategorijaOglasa (#PCDATA)>

<!ELEMENT DatumIsteka (#PCDATA)>

<!ELEMENT Cena (#PCDATA)>
<!ATTLIST Cena valuta CDATA "dinar">

<!ELEMENT TekstOglasa (#PCDATA)>

<!ELEMENT Oznaka (#PCDATA)>

<!ELEMENT Email (#PCDATA)>
<!ATTLIST Email tip (privatni|sluzbeni) #REQUIRED>

=== fanste98/ist2020/oglasi.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!DOCTYPE Oglasi SYSTEM "oglasi.dtd">
<Oglasi>
  <Oglas>
    <KategorijaOglasa>
      Automobili
    </KategorijaOglasa>
    <DatumIsteka>13.09.2020.</DatumIsteka>
    <Cena valuta="dinar">24000</Cena>
    <TekstOglasa>
      Ovo je neki oglas o automobilima.
    </TekstOglasa>
    <Oznaka>
      Oznaka1
    </Oznaka>
    <Oznaka>
      Oznaka2
    </Oznaka>
    <Email tip="privatni">
      petarpetrovic@gmail.com
    </Email>
    <Email tip="sluzbeni">
      prodautomobila@gmail.com
    </Email>
  </Oglas>
  <Oglas>
    <KategorijaOglasa>
      Stanovi
    </KategorijaOglasa>
    <DatumIsteka>20.09.2020.</DatumIsteka>
    <Cena valuta="euro">250</Cena>
    <TekstOglasa>
      Ovo je neki oglas za stan.
    </TekstOglasa>
    <Oznaka>
      Oznaka1
    </Oznaka>
    <Email tip="privatni">
      markomarkovic@gmail.com
    </Email>
    <Email tip="sluzbeni">
      prodstanova@gmail.com
    </Email>
  </Oglas>
</Oglasi>
